version: '3'
services:
  broker:
    image: broker
    environment:
      KEY_FILE: /root/pr.key
      KEY_PASS: azerty123
    ports:
      - 8883:8883
    networks:
      - net

  gateway:
    image: gateway
    environment:
      KEY_FILE: /root/pr.key
      KEY_PASS: azerty123
    ports:
      - 443:443
    networks:
      - net

networks:
  net: